### ISSUE TITLE
Gracefully handle semantically meaningless changes

### ISSUE THREAD

**Issue by Eh2406** [Byron/crates-index-diff-rs#16]
In https://github.com/rust-lang/crates.io/pull/5066 there are plans for the official index to be normalized to match the crates.io database. This unfortunately creates a lot of churn in the index. By churn I mean sorting the entries by version number, sorting the features, sorting the deps, etc. None of this should be semantically meaningful, but may lead to weird bugs in this crate.

This issue is to make sure that this crate handles these changes gracefully, hopefully before the index normalization is actually performed.

**Comment by Byron** [comment]
Thanks for the heads-up! I will be taking a stab at this today and will be using https://github.com/arlosi/crates.io-index as a basis to create a test-case from will hopefully be enough to make it able to cope with this.

Something I was wondering though: What if docs.rs would regenerate each version of each crate with a priority of -2? Would that not lead to nicer docs as they are now created by a much more recent `rustdoc`? If `docs.rs` had such capability, I could imagine it doing this once a year or so to normalize the looks of docs. There are of course a lot of arguments against that, number one coming to my mind being that fewest people presumably look at old version of the docs anyway.

**Comment by Eh2406** [comment]
That is a really interesting suggestion for the docs.rs team. I don't see how it's relevant to this attempt by the crates.io team too bring there two different databases In Sync with each other. What did I miss?

**Comment by Byron** [comment]
Probably it isn't, after all rebuilding everything can be achieved more easily than abusing bugs I thought `crates-index-diff` would exhibit. That was wrong though, having looked at the code I believe it would probably just go horribly wrong :D.

The reason I really like this task is that…

- …the test suite can be overhauled with `git-testtools` in tow
- …`gitoxide` was always lacking line-diffing capabilities and now is a chance to build a trial version of this
- …using `gitoxide` for diffing will definitely be a speedup

So in the end, `git2` will only be used for fetching, and the diff logic will be rebuilt to be agnostic to meaningless changes. Let's see how it pans out.

**Comment by Byron** [comment]
I have released [v11](https://github.com/Byron/crates-index-diff-rs/releases/tag/v11.0.0) which [addresses the normalization issue](https://github.com/Byron/crates-index-diff-rs/blob/eb148e512bc29cdc81f4eb35bda0a1819d9abd69/tests/index/changes_between_commits.rs#L71-L76) and will create a PR over at docs.rs shortly to upgrade to the new version.
