### ISSUE TITLE
Unexpected `Deleted` event for crate "dl"

### ISSUE THREAD

**Issue by jonhoo** [Byron/crates-index-diff-rs#20]
With this program:
```rust
use crates_index_diff::{Change, Index};

fn main() {
    let index = Index::from_path_or_cloned("crates.io-index").unwrap();
    let changes = index
        .changes(
            "feeacd1f399c353d020e7b9e0ddaf4b0628f9476",
            "c3d8f6d10335e8eb076dd594ec6d82e3f58ba24a",
        )
        .unwrap();
    for change in changes {
        match &change {
            Change::Added(cv) if cv.name == "dl" => {}
            Change::Yanked(cv) if cv.name == "dl" => {}
            Change::Deleted { name, .. } if name == "dl" => {}
            _ => continue,
        }

        eprintln!("{:?}", change);
    }
}
```

I get the result:

```console
$ git clone "https://github.com/rust-lang/crates.io-index.git"
$ cargo run --release
...
     Running `target/release/deleted-unexpectedly`
Deleted { name: "dl" }
```

However, `dl` is present in both commits ([in `from`](https://github.com/rust-lang/crates.io-index/blob/feeacd1f399c353d020e7b9e0ddaf4b0628f9476/2/dl) / [in `to`](https://github.com/rust-lang/crates.io-index/blob/c3d8f6d10335e8eb076dd594ec6d82e3f58ba24a/2/dl)) with no changes in between.

**Comment by jonhoo** [comment]
Now, I know there's a commit doing deletions in between ([this one](https://github.com/rust-lang/crates.io-index/commit/e36aee0142c61b2d707ab396bef534e79f57f240)), but it doesn't touch `dl` as far as I can tell.

**Comment by Byron** [comment]
Thanks a lot for letting me know, great catch!

I could reproduce the issue and fix it, with a new [patch release](https://github.com/Byron/crates-index-diff-rs/releases/tag/v11.1.6) to incorporate the change.

**Comment by jonhoo** [comment]
Excellent, thanks for the quick turnaround on a fix!
