### ISSUE TITLE
crates-index-diff 0.11.2 had breaking changes

### ISSUE THREAD

**Issue by jonhoo** [Byron/crates-index-diff-rs#23]
`crates-index-diff 0.11.2` bumped `git-repository` to major version 0.24, but since [`Index::repository` returns](https://docs.rs/crates-index-diff/11.2.0/crates_index_diff/struct.Index.html#method.repository) `git_repository::Repository`, this change is backwards-incompatible.

In particular, I hit this in a crate with:
```toml
[dependencies]
crates-index-diff = "0.11"
git-repository = "0.23"
```
```rust
fn count_versions(rep: &git_repository::Repository) { ... }
fn main() {
  let index = crates_index_diff::...;
  count_versions(index.repository());
}
```
which failed to build after running `cargo update` with:
```
error[E0308]: arguments to this function are incorrect
   --> src/incremental.rs:339:18
    |
339 |         exist += count_versions(index.repository(), &e)?;
    |                  ^^^^^^^^^^^^^^ ------------------  -- expected struct `git_repository::object::tree::EntryRef`, found struct `git_repository::object::tree::iter::EntryRef`
    |                                 |
    |                                 expected struct `git_repository::Repository`, found struct `git_repository::types::Repository`
    |
    = note: expected reference `&git_repository::Repository`
               found reference `&git_repository::types::Repository`
    = note: perhaps two different versions of crate `git_repository` are being used?
    = note: expected reference `&git_repository::object::tree::EntryRef<'_, '_>`
               found reference `&git_repository::object::tree::iter::EntryRef<'_, '_>`
    = note: perhaps two different versions of crate `git_repository` are being used? 
```

**Comment by Byron** [comment]
Thanks for letting me know!

I will try to be more careful with that. I got a bit over-reliant on `cargo smart-release` which takes care of version bumps, but only based on commit messages that do indicate something is breaking. Thus, when upgrading `git-repository` it was upon me to recognize this as breaking change, but that didn't happen.

In any case, v11.2 has been yanked and [v12.0 as been released](https://github.com/Byron/crates-index-diff-rs/releases/tag/v12.0.0) in its place.
