### ISSUE TITLE
Add option to disable serde

### ISSUE THREAD

**Issue by jyn514** [Byron/crates-index-diff-rs#6]
About half of the dependencies of `crates-index-diff` come from `serde`, `serde_derive`, and `serde_json`. It looks like `serde_json` is used for parsing the diff, so maybe it's not get feasible to get rid of that, but it would be nice to make `serde` and `serde_derive` optional.

**Comment by Byron** [comment]
Thanks for checking, and for engaging with this crate!
What I could imagine is to have a 'raw' version of the main functions, which return strings instead of parsed structures.

Since I myself have no use for it, it will probably take a while before I pick it up.

**Comment by jyn514** [comment]
Sorry, maybe I'm misunderstanding - I thought that serde wasn't used for anything except for parsing the diff line? You're saying it's used for something else too?

**Comment by Byron** [comment]
Probably - every method that returns `CrateVersion` relies on the aforementioned crates to function. The whole existence of this crate is justified to be able to do that. Maybe there is a use case to omit `CrateVersion` entirely for those who want to parse Json themselves.

**Comment by jyn514** [comment]
Ah ok, this wouldn't make sense to remove then.
